Update dockcross scripts

diff --git a/docker/dockcross-arm64 b/docker/dockcross-arm64
--- a/docker/dockcross-arm64
+++ b/docker/dockcross-arm64
@@ -6,11 +6,11 @@ DEFAULT_DOCKCROSS_IMAGE=dockcross/linux-arm64:latest
 # Helpers
 #
 err() {
-    echo -e >&2 ERROR: $@\\n
+    echo -e >&2 "ERROR: $*\n"
 }
 
 die() {
-    err $@
+    err "$*"
     exit 1
 }
 
@@ -41,20 +41,20 @@ command:update-image() {
 }
 
 help:update-image() {
-    echo Pull the latest $FINAL_IMAGE .
+    echo "Pull the latest $FINAL_IMAGE ."
 }
 
 command:update-script() {
     if cmp -s <( $OCI_EXE run --rm $FINAL_IMAGE ) $0; then
-        echo $0 is up to date
+        echo "$0 is up to date"
     else
-        echo -n Updating $0 '... '
+        echo -n "Updating $0 ... "
         $OCI_EXE run --rm $FINAL_IMAGE > $0 && echo ok
     fi
 }
 
 help:update-image() {
-    echo Update $0 from $FINAL_IMAGE .
+    echo "Update $0 from $FINAL_IMAGE ."
 }
 
 command:update() {
@@ -63,7 +63,7 @@ command:update() {
 }
 
 help:update() {
-    echo Pull the latest $FINAL_IMAGE, and then update $0 from that.
+    echo "Pull the latest $FINAL_IMAGE, and then update $0 from that."
 }
 
 command:help() {
@@ -187,6 +187,8 @@ FINAL_ARGS=${ARG_ARGS-${DOCKCROSS_ARGS}}
 UBUNTU_ON_WINDOWS=$([ -e /proc/version ] && grep -l Microsoft /proc/version || echo "")
 # MSYS, Git Bash, etc.
 MSYS=$([ -e /proc/version ] && grep -l MINGW /proc/version || echo "")
+# CYGWIN
+CYGWIN=$([ -e /proc/version ] && grep -l CYGWIN /proc/version || echo "")
 
 if [ -z "$UBUNTU_ON_WINDOWS" -a -z "$MSYS" ]; then
     USER_IDS=(-e BUILDER_UID="$( id -u )" -e BUILDER_GID="$( id -g )" -e BUILDER_USER="$( id -un )" -e BUILDER_GROUP="$( id -gn )")
@@ -209,6 +211,11 @@ elif [ -n "$MSYS" ]; then
     HOST_PWD=$PWD
     HOST_PWD=${HOST_PWD/\//}
     HOST_PWD=${HOST_PWD/\//:\/}
+elif [ -n "$CYGWIN" ]; then
+    for f in pwd readlink cygpath ; do
+        test -n "$(type "${f}" )" || { echo >&2 "Missing functionality (${f}) (in cygwin)." ; exit 1 ; } ;
+    done ;
+    HOST_PWD="$( cygpath -w "$( readlink -f "$( pwd ;)" ; )" ; )" ;
 else
     HOST_PWD=$PWD
     [ -L $HOST_PWD ] && HOST_PWD=$(readlink $HOST_PWD)
@@ -221,7 +228,11 @@ fi
 
 HOST_VOLUMES=
 if [ -e "$SSH_DIR" -a -z "$MSYS" ]; then
-    HOST_VOLUMES+="-v $SSH_DIR:/home/$(id -un)/.ssh"
+    if test -n "${CYGWIN}" ; then
+      HOST_VOLUMES+="-v $(cygpath -w ${SSH_DIR} ; ):/home/$(id -un)/.ssh" ;
+    else
+      HOST_VOLUMES+="-v $SSH_DIR:/home/$(id -un)/.ssh" ;
+    fi ;
 fi
 
 #------------------------------------------------------------------------------
