update all dockcross scripts via dockcross-xxx update

diff --git a/docker/dockcross-armv7a b/docker/dockcross-armv7a
--- a/docker/dockcross-armv7a
+++ b/docker/dockcross-armv7a
@@ -22,11 +22,22 @@ has() {
     type -t $kind:$name | grep -q function
 }
 
+# If OCI_EXE is not already set, search for a container executor (OCI stands for "Open Container Initiative")
+if [ -z "$OCI_EXE" ]; then
+    if which docker >/dev/null 2>/dev/null; then
+        OCI_EXE=docker
+    elif which podman >/dev/null 2>/dev/null; then
+        OCI_EXE=podman
+    else
+        die "Cannot find a container executor. Search for docker and podman."
+    fi
+fi
+
 #------------------------------------------------------------------------------
 # Command handlers
 #
 command:update-image() {
-    docker pull $FINAL_IMAGE
+    $OCI_EXE pull $FINAL_IMAGE
 }
 
 help:update-image() {
@@ -34,11 +45,11 @@ help:update-image() {
 }
 
 command:update-script() {
-    if cmp -s <( docker run --rm $FINAL_IMAGE ) $0; then
+    if cmp -s <( $OCI_EXE run --rm $FINAL_IMAGE ) $0; then
         echo $0 is up to date
     else
         echo -n Updating $0 '... '
-        docker run --rm $FINAL_IMAGE > $0 && echo ok
+        $OCI_EXE run --rm $FINAL_IMAGE > $0 && echo ok
     fi
 }
 
@@ -219,13 +230,27 @@ fi
 TTY_ARGS=
 tty -s && [ -z "$MSYS" ] && TTY_ARGS=-ti
 CONTAINER_NAME=dockcross_$RANDOM
-docker run $TTY_ARGS --name $CONTAINER_NAME \
+$OCI_EXE run $TTY_ARGS --name $CONTAINER_NAME \
     -v "$HOST_PWD":/work \
     $HOST_VOLUMES \
     "${USER_IDS[@]}" \
     $FINAL_ARGS \
     $FINAL_IMAGE "$@"
 run_exit_code=$?
+
+# Attempt to delete container
+rm_output=$($OCI_EXE rm -f $CONTAINER_NAME 2>&1)
+rm_exit_code=$?
+if [[ $rm_exit_code != 0 ]]; then
+  if [[ "$CIRCLECI" == "true" ]] && [[ $rm_output == *"Driver btrfs failed to remove"* ]]; then
+    : # Ignore error because of https://circleci.com/docs/docker-btrfs-error/
+  else
+    echo "$rm_output"
+    exit $rm_exit_code
+  fi
+fi
+
+exit $run_exit_code
 
 ################################################################################
 #
diff --git a/docker/dockcross-ppc64 b/docker/dockcross-ppc64
--- a/docker/dockcross-ppc64
+++ b/docker/dockcross-ppc64
@@ -1,6 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-DEFAULT_DOCKCROSS_IMAGE=dockcross/linux-ppc64le
+DEFAULT_DOCKCROSS_IMAGE=dockcross/linux-ppc64le:latest
 
 #------------------------------------------------------------------------------
 # Helpers
@@ -22,11 +22,22 @@ has() {
     type -t $kind:$name | grep -q function
 }
 
+# If OCI_EXE is not already set, search for a container executor (OCI stands for "Open Container Initiative")
+if [ -z "$OCI_EXE" ]; then
+    if which docker >/dev/null 2>/dev/null; then
+        OCI_EXE=docker
+    elif which podman >/dev/null 2>/dev/null; then
+        OCI_EXE=podman
+    else
+        die "Cannot find a container executor. Search for docker and podman."
+    fi
+fi
+
 #------------------------------------------------------------------------------
 # Command handlers
 #
 command:update-image() {
-    docker pull $FINAL_IMAGE
+    $OCI_EXE pull $FINAL_IMAGE
 }
 
 help:update-image() {
@@ -34,11 +45,11 @@ help:update-image() {
 }
 
 command:update-script() {
-    if cmp -s <( docker run $FINAL_IMAGE ) $0; then
+    if cmp -s <( $OCI_EXE run --rm $FINAL_IMAGE ) $0; then
         echo $0 is up to date
     else
         echo -n Updating $0 '... '
-        docker run $FINAL_IMAGE > $0 && echo ok
+        $OCI_EXE run --rm $FINAL_IMAGE > $0 && echo ok
     fi
 }
 
@@ -98,6 +109,7 @@ while [[ $# != 0 ]]; do
     case $1 in
 
         --)
+            shift
             break
             ;;
 
@@ -171,29 +183,84 @@ fi
 # Set the docker run extra args (if any)
 FINAL_ARGS=${ARG_ARGS-${DOCKCROSS_ARGS}}
 
-# If we are not running via boot2docker
-if [ -z $DOCKER_HOST ]; then
+# Bash on Ubuntu on Windows
+UBUNTU_ON_WINDOWS=$([ -e /proc/version ] && grep -l Microsoft /proc/version || echo "")
+# MSYS, Git Bash, etc.
+MSYS=$([ -e /proc/version ] && grep -l MINGW /proc/version || echo "")
+
+if [ -z "$UBUNTU_ON_WINDOWS" -a -z "$MSYS" ]; then
     USER_IDS=(-e BUILDER_UID="$( id -u )" -e BUILDER_GID="$( id -g )" -e BUILDER_USER="$( id -un )" -e BUILDER_GROUP="$( id -gn )")
+fi
+
+# Change the PWD when working in Docker on Windows
+if [ -n "$UBUNTU_ON_WINDOWS" ]; then
+    WSL_ROOT="/mnt/"
+    CFG_FILE=/etc/wsl.conf
+	if [ -f "$CFG_FILE" ]; then
+		CFG_CONTENT=$(cat $CFG_FILE | sed -r '/[^=]+=[^=]+/!d' | sed -r 's/\s+=\s/=/g')
+		eval "$CFG_CONTENT"
+		if [ -n "$root" ]; then
+			WSL_ROOT=$root
+		fi
+	fi
+    HOST_PWD=`pwd -P`
+    HOST_PWD=${HOST_PWD/$WSL_ROOT//}
+elif [ -n "$MSYS" ]; then
+    HOST_PWD=$PWD
+    HOST_PWD=${HOST_PWD/\//}
+    HOST_PWD=${HOST_PWD/\//:\/}
+else
+    HOST_PWD=$PWD
+    [ -L $HOST_PWD ] && HOST_PWD=$(readlink $HOST_PWD)
+fi
+
+# Mount Additional Volumes
+if [ -z "$SSH_DIR" ]; then
+    SSH_DIR="$HOME/.ssh"
+fi
+
+HOST_VOLUMES=
+if [ -e "$SSH_DIR" -a -z "$MSYS" ]; then
+    HOST_VOLUMES+="-v $SSH_DIR:/home/$(id -un)/.ssh"
 fi
 
 #------------------------------------------------------------------------------
 # Now, finally, run the command in a container
 #
-docker run --rm \
-    -v $PWD:/work \
+TTY_ARGS=
+tty -s && [ -z "$MSYS" ] && TTY_ARGS=-ti
+CONTAINER_NAME=dockcross_$RANDOM
+$OCI_EXE run $TTY_ARGS --name $CONTAINER_NAME \
+    -v "$HOST_PWD":/work \
+    $HOST_VOLUMES \
     "${USER_IDS[@]}" \
     $FINAL_ARGS \
     $FINAL_IMAGE "$@"
+run_exit_code=$?
+
+# Attempt to delete container
+rm_output=$($OCI_EXE rm -f $CONTAINER_NAME 2>&1)
+rm_exit_code=$?
+if [[ $rm_exit_code != 0 ]]; then
+  if [[ "$CIRCLECI" == "true" ]] && [[ $rm_output == *"Driver btrfs failed to remove"* ]]; then
+    : # Ignore error because of https://circleci.com/docs/docker-btrfs-error/
+  else
+    echo "$rm_output"
+    exit $rm_exit_code
+  fi
+fi
+
+exit $run_exit_code
 
 ################################################################################
 #
 # This image is not intended to be run manually.
 #
 # To create a dockcross helper script for the
-# dockcross/linux-armv7 image, run:
+# dockcross/linux-ppc64le:latest image, run:
 #
-# docker run --rm dockcross/linux-armv7 > dockcross-linux-armv7
-# chmod +x dockcross-linux-armv7
+# docker run --rm dockcross/linux-ppc64le:latest > dockcross-linux-ppc64le-latest
+# chmod +x dockcross-linux-ppc64le-latest
 #
 # You may then wish to move the dockcross script to your PATH.
 #
